version: '3.8'

services:
  nestjs-server:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - aesthete-db
    environment:
      - DATABASE_URL=postgresql://postgres:SAEZurich2023@aesthete-db:5432/aesthete-db
    command: ['yarn', 'run', 'start:prod']

  aesthete-db:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=SAEZurich2023
      - POSTGRES_DB=aesthete-db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres:
